const authLayer=document.createElement('div');authLayer.className='auth-layer';authLayer.innerHTML=`<section class="auth-card" role="dialog" aria-modal="true"><button class="auth-close" type="button">×</button><p class="eyebrow">管理者認證</p><h2>管理員帳密設定</h2><p>輸入目前密碼後，可以修改帳號或設定新密碼。</p><form id="accountForm"><label>管理員帳號<input id="accountUsername" required minlength="3" maxlength="64"></label><label>目前密碼<input id="currentPassword" type="password" required minlength="10" maxlength="128"></label><label>新密碼（不修改可留空）<input id="newPassword" type="password" minlength="10" maxlength="128"></label><p id="accountError" class="auth-error"></p><button type="submit">儲存修改</button></form><button id="logoutButton" class="secondary" type="button">登出</button></section>`;document.body.appendChild(authLayer);
const adminButton=document.createElement('button');adminButton.className='admin-button';document.querySelector('aside').insertBefore(adminButton,document.querySelector('.side-note'));
let currentUser='';
async function checkAuth(){const status=await fetch('/api/auth/status').then(response=>response.json());if(!status.authenticated){location.replace('/login.html');return false}currentUser=status.username;adminButton.textContent=`管理員：${currentUser}`;return true}
adminButton.onclick=()=>{document.querySelector('#accountUsername').value=currentUser;document.querySelector('#currentPassword').value='';document.querySelector('#newPassword').value='';document.querySelector('#accountError').textContent='';authLayer.classList.add('open')};
document.querySelector('.auth-close').onclick=()=>authLayer.classList.remove('open');
document.querySelector('#accountForm').onsubmit=async event=>{event.preventDefault();const response=await fetch('/api/auth/credentials',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:document.querySelector('#accountUsername').value,current_password:document.querySelector('#currentPassword').value,new_password:document.querySelector('#newPassword').value})}),data=await response.json();if(!response.ok){document.querySelector('#accountError').textContent=data.error||'修改失敗';return}currentUser=data.username;adminButton.textContent=`管理員：${currentUser}`;authLayer.classList.remove('open')};
document.querySelector('#logoutButton').onclick=async()=>{await fetch('/api/auth/logout',{method:'POST'});location.replace('/')};
checkAuth();setInterval(checkAuth,30000);
